version: "3.6"

services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'localhost'
    environment:
      - GITLAB_ROOT_EMAIL="root@local"
      - GITLAB_ROOT_PASSWORD="adminadmin" #if for some reason it doesn't work exec into container and do gitlab-rake "gitlab:password:reset" username is root
      - EXTERNAL_URL="http://localhost"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - etc:/etc/gitlab
      - log:/var/log/gitlab
      - opt:/var/opt/gitlab

volumes:
  etc:
  log:
  opt:
